# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chrastil Lab Documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://chrastillab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
theme: just-the-docs

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/brainnn.ico"
mermaid:
  version: "9.1.3"

aux_links:
  "Chrastil Lab Repos":
    - "//github.com/chrastillab"
  "Spatial Neuroscience Repos":
    - "//github.com/chrastillab"

aux_links_new_tab: true

# Editing Components provides links to the github editing page
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/chrastillab/chrastillab.github.io" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Collection Settings

collections:
  coding:
    permalink: "/:collection/:path/"
    output: true
  server_management:
    permalink: "/:collection/:path/"
    output: true
  misc:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  collections:
    coding:
      name: "Coding"
    server_management:
      name: "Server Management"
    misc:
      name: "Miscellaneous"

# Enabling line number for code
compress_html:
  ignore:
    envs: all  

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Callout settings
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Important
    color: blue
  highlight:
    title: Highlight
    color: yellow
  new:
    title: new
    color: green

exclude:
  - .obsidian # I use obsidian to editing Markdown files, here I need to ignore the autogenerated obsidian folder
  - obsidian-templates