# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chrastil Lab Documentation
email: spatialneuroscience@uci.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Chrastil Lab Code Documentation Repository on GitHub! This repository serves as the central hub for organizing and sharing the coding documentation related to the research and projects conducted by the Chrastil Lab.
baseurl: "/" # the subpath of your site, e.g. /blog
#domain: "chrastillab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://chrastillab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username: chrastillab

# Build settings
theme: just-the-docs
plugins:
  - jekyll-redirect-from

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/brainnn.png"
mermaid:
  version: "9.1.3"

aux_links:
  "Chrastil Lab Repos":
    - "//github.com/chrastillab"
  "Spatial Neuroscience Repos":
    - "//github.com/chrastillab"

aux_links_new_tab: true

# Editing Components provides links to the github editing page
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/chrastillab/chrastillab.github.io" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Collection Settings

collections:
  coding:
    permalink: "/:collection/:path/"
    output: true
  server_management:
    permalink: "/:collection/:path/"
    output: true
  misc:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  collections:
    server_management:
      name: "Server Management"
    misc:
      name: "Miscellaneous"

# Enabling line number for code
compress_html:
  ignore:
    envs: all  

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true